### ISSUE TITLE
Demo not working 

### ISSUE THREAD

**Issue by rgbkrk** [reasonml-community/Mareo#1]
Console for https://reasonml-community.github.io/Mareo/ gives a 404 for `https://reasonml-community.github.io/lib/es6_global/src/main.js`.

**Comment by chenglou** [comment]
Eh I don't see this in any browser. Which one are you using?

**Comment by rgbkrk** [comment]
```
Google Chrome | 61.0.3163.79 (Official Build) (64-bit)
Revision | 2bd57c7d956c47bc51eff132dd114136ec0a6db7-refs/branch-heads/3163@{#1092}
OS | Mac OS X
```

![screen shot 2017-09-18 at 11 43 44 am](https://user-images.githubusercontent.com/836375/30558564-c5e5f1ee-9c66-11e7-88a7-fdf04c39ae60.png)

**Comment by chenglou** [comment]
Fixed, thanks. This is due to Chrome 61 ironically starting to support es6 modules + some chrome restrictions I believe. For now, for the demo, I'm just shipping the generated bundle.

I guess the production-time native import dream is still a bit away! Still pretty good at dev time though.

**Comment by rgbkrk** [comment]
Ha, that is awesome.
